const express = require("express");
const bodyParser = require("body-parser");
const cors = require("cors");
const fs = require("fs");
const { v4: uuid } = require("uuid");

const app = express();
app.use(cors());
app.use(bodyParser.json());

let modules = JSON.parse(fs.readFileSync("./server/modules.json"));

/* ดึงโมดูลทั้งหมด */
app.get("/api/modules", (req,res)=>{
  res.json(modules);
});

/* ตรวจฟรี/เสียเงิน */
app.post("/api/check-module",(req,res)=>{
  const m = modules.find(x=>x.id===req.body.id);
  res.json(m);
});

/* AI Builder (mock) */
app.post("/api/ai-build",(req,res)=>{
  const prompt = req.body.prompt;

  res.json({
    html:`<h1>${prompt}</h1><p>Generated by AI</p>`
  });
});

/* Macro Recorder */
app.post("/api/record",(req,res)=>{
  const data = req.body;
  fs.writeFileSync(`./server/macro-${uuid()}.json`,JSON.stringify(data,null,2));
  res.json({status:"saved"});
});

app.listen(3000,()=>console.log("API running :3000"));
const paymentRoutes = require("./payment");
app.use("/api/payment", paymentRoutes);
